### ISSUE TITLE
tag `v0.0.9` doesn't match branch `v0.0.9`

### ISSUE THREAD

**Issue by lukasz-mitka** [engineerd/configurator#46]
See the title.

**Comment by rajatjindal** [comment]
Hi @lukasz-mitka thank you for reporting this issue. I am pretty sure I did some mess up when cutting the v0.0.9 release 

(I was doing the release for the first time).

I am looking into it and will get back to you.

**Comment by rajatjindal** [comment]
just purely for my knowledge, how did you found this discrepancy and was there any impact due to this. 

I am trying to understand pros/cons of deleting/re-pushing the tag.

**Comment by lukasz-mitka** [comment]
I was trying to pin the action to the specific hash (security) instead of tag.
Copied the hash from the tag and it ended up erroring on missing resources.

I'd advice on force pushing the updated tag.

**Comment by rajatjindal** [comment]
Hii @lukasz-mitka  thank you for your patience. 

I've tagged a new release `v0.0.10` and changed the process to keep the release bits in main branch instead of creating a new release branch.

hopefully this will ensure we do not run into this kind of issue again.

I apologize for the inconvenience and appreciate that you took time to bring this to our notice. 

I would like to close the mismatch reported in this ticket as won't fix. do you see any concerns with that.

**Comment by lukasz-mitka** [comment]
Hi @rajatjindal,
Thank you!
I would still force push the updated `v0.0.9` tag for consistency, but it doesn't affect me anymore, so leaving it entirely up to you.
